/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ptit.view;

import com.ptit.dao.BillDAO;
import com.ptit.dao.DetailBillDAO;
import com.ptit.model.Accessories;
import com.ptit.model.DetailBill;
import com.ptit.model.Bill;
import com.ptit.model.Car;
import com.ptit.model.Customer;
import com.ptit.model.Service;
import static com.ptit.utility.Validation.isAmountValid;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUONGNV
 */
public class BillView extends javax.swing.JFrame {

    DefaultTableModel model;
    Bill bill;
    BillDAO billDAO;
    DetailBillDAO detailBillDAO;
    List<Accessories> acclist;
    List<Service> services;
    List<DetailBill> serviceBills;
    List<DetailBill> accBills;
    Locale localeVN;
    NumberFormat formatPrice;

    public BillView(List<Service> slist, List<Accessories> alist, List<DetailBill> serBills, List<DetailBill> accBills, Car car, Customer customer, Bill bill) {
        initComponents();
        this.setLocationRelativeTo(null);
        localeVN = new Locale("vi", "VN");
        formatPrice = NumberFormat.getCurrencyInstance(localeVN);
        billDAO = new BillDAO();
        detailBillDAO = new DetailBillDAO();
        this.bill = bill;
        acclist = alist;
        services = slist;
        serviceBills = serBills;
        this.accBills = accBills;

        jLabelGetName.setText(customer.getFullName());
        jLabelGetAddress.setText(customer.getAddress());
        jLabelGetPhone.setText(customer.getPhone());
        jLabelGetModel.setText(car.getModel());
        jLabelGetLicense.setText(car.getLicense());

        int i = 1;
        if (!serviceBills.isEmpty()) {
            model = (DefaultTableModel) this.jTableService.getModel();
            model.setRowCount(0);

            for (int j = 0; j < services.size(); j++) {
                int price = serviceBills.get(j).getAmount() * (services.get(j).getServicePrice());
                model.addRow(new Object[]{i++, services.get(j).getServiceID(), services.get(j).getServiceName(), serviceBills.get(j).getAmount(), services.get(j).getServicePrice(), price});
            }
        }

        if (!accBills.isEmpty()) {
            model = (DefaultTableModel) this.jTableAccessories.getModel();
            model.setRowCount(0);
            i = 1;
            for (int k = 0; k < acclist.size(); k++) {
                int price = accBills.get(k).getAmount() * (acclist.get(k).getAccessoriesPrice());
                model.addRow(new Object[]{i++, acclist.get(k).getAccessoriesID(), acclist.get(k).getAccessoriesName(), accBills.get(k).getAmount(), acclist.get(k).getAccessoriesPrice(), price});
            }
        }

        String price = formatPrice.format(getSum());
        jLabelSum.setText(price);
    }

    private int getSum() {
        int sum = 0;
        for (int i = 0; i < jTableAccessories.getRowCount(); i++) {
            sum += Integer.parseInt(jTableAccessories.getValueAt(i, 5).toString());
        }
        for (int i = 0; i < jTableService.getRowCount(); i++) {
            sum += Integer.parseInt(jTableService.getValueAt(i, 5).toString());
        }
        return sum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelGetName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelGetAddress = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelGetPhone = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelGetModel = new javax.swing.JLabel();
        jLabelLicense = new javax.swing.JLabel();
        jLabelGetLicense = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableService = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAccessories = new javax.swing.JTable();
        jButtonConfirm = new javax.swing.JButton();
        jLabelMoney = new javax.swing.JLabel();
        jLabelSum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setText("Tên khách hàng :");

        jLabelGetName.setText("Tên khách hàng");

        jLabelAddress.setText("Địa chỉ :");

        jLabelGetAddress.setText("Địa chỉ");

        jLabelPhone.setText("Số điện thoại :");

        jLabelGetPhone.setText("Số điện thoại");

        jLabelModel.setText("Loại xe :");

        jLabelGetModel.setText("Loại xe");

        jLabelLicense.setText("Biển số:");

        jLabelGetLicense.setText("Biển số");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã dịch vụ", "Tên dịch vụ", "Số lượng", "Tiền công", "Thành tiền"
            }
        ));
        jTableService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableService);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableAccessories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã LK/PT", "Tên LK/PT", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jTableAccessories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAccessoriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAccessories);

        jButtonConfirm.setText("Xác nhận");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabelMoney.setText("Tổng tiền :");

        jLabelSum.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGetName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGetPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabelModel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGetModel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLicense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelGetLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addComponent(jScrollPane2)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButtonConfirm)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSum, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabelGetName)
                    .addComponent(jLabelAddress)
                    .addComponent(jLabelGetAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone)
                    .addComponent(jLabelGetPhone)
                    .addComponent(jLabelModel)
                    .addComponent(jLabelGetModel)
                    .addComponent(jLabelLicense)
                    .addComponent(jLabelGetLicense))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoney)
                    .addComponent(jLabelSum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirm)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
        bill.setTotalMoney(getSum());
        billDAO.updateBill(bill);

        this.setVisible(false);
        ChooseEmployeeSlotView chooseEmployeeSlotView = new ChooseEmployeeSlotView();
        chooseEmployeeSlotView.setVisible(true);
        chooseEmployeeSlotView.setTitle("Chọn nhân viên slot");

    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTableServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServiceMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) this.jTableService.getModel();
        int index = jTableService.getSelectedRow();
        DetailBill serviceBill = serviceBills.get(index);
        String[] options = {"Sửa", "Xóa", "Hủy"};
        int choose = JOptionPane.showOptionDialog(null, "Chọn để tiếp tục, hủy để quay lại",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        switch (choose) {
            case 0:
                String m = JOptionPane.showInputDialog(this, "Nhập số lượng", jTableService.getValueAt(index, 3));
                if (isAmountValid(m)) {
                    serviceBill.setAmount(Integer.parseInt(m));
                    int price = serviceBills.get(index).getAmount() * (services.get(index).getServicePrice());
                    model.setValueAt(m, index, 3);
                    model.setValueAt(String.valueOf(price), index, 5);
                    String sql = "UPDATE ServiceBill SET amount = ? WHERE serviceID = ? AND billID = ?";
                    detailBillDAO.updateDetailBill(sql, serviceBill);
                }
                break;
            case 1:
                model.removeRow(index);
                String sql = "DELETE FROM ServiceBill WHERE serviceID = ? AND billID = ?";
                detailBillDAO.deleteDetailBill(sql, serviceBill);
                serviceBills.remove(index);
                services.remove(index);
                break;
            default:
                break;
        }
        String price = formatPrice.format(getSum());
        jLabelSum.setText(price);
    }//GEN-LAST:event_jTableServiceMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTableAccessoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAccessoriesMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) this.jTableAccessories.getModel();
        int index = jTableAccessories.getSelectedRow();
        DetailBill accessoriesBill = accBills.get(index);
        String[] options = {"Sửa", "Xóa", "Hủy"};
        int choose = JOptionPane.showOptionDialog(null, "Chọn để tiếp tục, hủy để quay lại",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        switch (choose) {
            case 0:
                String m = JOptionPane.showInputDialog(this, "Nhập số lượng", jTableAccessories.getValueAt(index, 3));
                if (isAmountValid(m)) {
                    accessoriesBill.setAmount(Integer.parseInt(m));
                    int price = accBills.get(index).getAmount() * (acclist.get(index).getAccessoriesPrice());
                    model.setValueAt(m, index, 3);
                    model.setValueAt(String.valueOf(price), index, 5);
                    String sql = "UPDATE AccessoriesBill SET amount = ? WHERE accessoriesID = ? AND billID = ?";
                    detailBillDAO.updateDetailBill(sql, accessoriesBill);
                }
                break;
            case 1:
                model.removeRow(index);
                String sql = "DELETE FROM AccessoriesBill WHERE accessoriesID = ? AND billID = ?";
                detailBillDAO.deleteDetailBill(sql, accessoriesBill);
                accBills.remove(index);
                acclist.remove(index);
                break;
            default:
                break;
        }
        String price = formatPrice.format(getSum());
        jLabelSum.setText(price);
    }//GEN-LAST:event_jTableAccessoriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillView(null, null, null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelGetAddress;
    private javax.swing.JLabel jLabelGetLicense;
    private javax.swing.JLabel jLabelGetModel;
    private javax.swing.JLabel jLabelGetName;
    private javax.swing.JLabel jLabelGetPhone;
    private javax.swing.JLabel jLabelLicense;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAccessories;
    private javax.swing.JTable jTableService;
    // End of variables declaration//GEN-END:variables
}
