/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ptit.view;

import com.ptit.dao.DetailBillDAO;
import com.ptit.dao.AccessoriesDAO;
import com.ptit.dao.BillDAO;
import com.ptit.dao.ServiceDAO;
import com.ptit.model.Accessories;
import com.ptit.model.Bill;
import com.ptit.model.Car;
import com.ptit.model.Customer;
import com.ptit.model.DetailBill;
import com.ptit.model.Service;
import static com.ptit.utility.Validation.isAmountValid;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUONGNV
 */
public class ChooseServiceView extends javax.swing.JFrame {

    boolean check;
    int billID;
    Bill bill;
    BillDAO billDAO;
    Customer customer;
    Car car;
    List<Accessories> acclist;
    List<Service> services;
    List<DetailBill> serviceBills;
    List<DetailBill> accBills;
    ServiceDAO serviceDAO;
    AccessoriesDAO accessoriesDAO;
    DetailBillDAO detailBillDAO;
    DefaultTableModel model;

    /**
     * Creates new form ChooseServiceView
     */
    public ChooseServiceView(Car c, Customer cus) {
        initComponents();
        this.setLocationRelativeTo(null);
        car = c;
        customer = cus;
        bill = new Bill(customer.getCustomerID(), car.getCarID(), 0);

        services = new ArrayList<>();
        acclist = new ArrayList<>();
        serviceBills = new ArrayList<>();
        accBills = new ArrayList<>();
        billDAO = new BillDAO();
        serviceDAO = new ServiceDAO();
        accessoriesDAO = new AccessoriesDAO();
        detailBillDAO = new DetailBillDAO();
        model = (DefaultTableModel) this.jTableService.getModel();

        jLabelGetlName.setText(customer.getFullName());
        jLabelGetModel.setText(car.getModel());
        jLabelGetMaker.setText(car.getMaker());
        jLabelGetLicense.setText(car.getLicense());
        jLabelGetNote.setText(car.getNote());

        billID = billDAO.insertBill(bill);
        bill.setBillID(billID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCusName = new javax.swing.JLabel();
        jLabelGetlName = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelGetModel = new javax.swing.JLabel();
        jLabelMaker = new javax.swing.JLabel();
        jLabelGetMaker = new javax.swing.JLabel();
        jLabelLicense = new javax.swing.JLabel();
        jLabelGetLicense = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jLabelGetNote = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableService = new javax.swing.JTable();
        jButtonDone = new javax.swing.JButton();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCusName.setText("Tên khách hàng :");

        jLabelGetlName.setText("Tên khách hàng");

        jLabelModel.setText("Loại xe :");

        jLabelGetModel.setText("Loại xe");

        jLabelMaker.setText("Nhà sản xuất :");

        jLabelGetMaker.setText("Nhà sản xuất");

        jLabelLicense.setText("Biển số :");

        jLabelGetLicense.setText("Biển số");

        jLabelNote.setText("Mô tả :");

        jLabelGetNote.setText("Ghi chú");

        jLabelName.setText("Nhập tên :");

        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTableService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ/ linh kiện", "Tên dịch vụ/ linh kiện", "Đơn giá(VND)"
            }
        ));
        jTableService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableService);

        jButtonDone.setText("Xong");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dịch vụ", "Linh kiện" }));

        jLabelType.setText("Mục tìm kiếm :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGetModel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMaker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGetMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGetLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCusName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGetlName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGetNote, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jButtonDone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCusName)
                    .addComponent(jLabelGetlName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModel)
                    .addComponent(jLabelGetModel)
                    .addComponent(jLabelMaker)
                    .addComponent(jLabelGetMaker)
                    .addComponent(jLabelLicense)
                    .addComponent(jLabelGetLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNote)
                    .addComponent(jLabelGetNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButtonDone)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        String key = this.jTextFieldName.getText();
        if (key.equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else {
            String typeSearch = this.jComboBoxType.getSelectedItem().toString();
            if (typeSearch.equals("Dịch vụ")) {
                check = true;
                List<Service> list = serviceDAO.selectService(key);
                if (list.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả");
                } else {
                    for (Service service : list) {
                        model.addRow(new Object[]{service.getServiceID(), service.getServiceName(), service.getServicePrice()});
                    }
                }
            } else {
                check = false;
                List<Accessories> list = accessoriesDAO.selectAccessories(key);
                if (list.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả");
                } else {
                    for (Accessories acc : list) {
                        model.addRow(new Object[]{acc.getAccessoriesID(), acc.getAccessoriesName(), acc.getAccessoriesPrice()});
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServiceMouseClicked
        // TODO add your handling code here:
        int index = jTableService.getSelectedRow();
        if (check) {
            String m = JOptionPane.showInputDialog(this, "Nhập số lượng", 0);
            if (isAmountValid(m)) {
                Service service = new Service();
                DetailBill serviceBill = new DetailBill();
                service.setServiceID((String) model.getValueAt(index, 0));
                service.setServiceName((String) model.getValueAt(index, 1));
                service.setServicePrice((Integer) model.getValueAt(index, 2));
                services.add(service);

                serviceBill.setBillID(billID);
                serviceBill.setDetailBill((String) model.getValueAt(index, 0));
                serviceBill.setAmount(Integer.parseInt(m));
                serviceBills.add(serviceBill);
                String sql = "INSERT INTO ServiceBill VALUES(?,?,?)";
                detailBillDAO.insertDetailBill(sql, serviceBill);
            }
        } else {
            String m = JOptionPane.showInputDialog(this, "Nhập số lượng", 0);
            if (isAmountValid(m)) {
                Accessories acc = new Accessories();
                DetailBill accessoriesBill = new DetailBill();
                acc.setAccessoriesID((String) model.getValueAt(index, 0));
                acc.setAccessoriesName((String) model.getValueAt(index, 1));
                acc.setAccessoriesPrice((Integer) model.getValueAt(index, 2));
                acclist.add(acc);

                accessoriesBill.setBillID(billID);
                accessoriesBill.setDetailBill((String) model.getValueAt(index, 0));
                accessoriesBill.setAmount(Integer.parseInt(m));
                accBills.add(accessoriesBill);
                String sql = "INSERT INTO AccessoriesBill VALUES(?,?,?)";
                detailBillDAO.insertDetailBill(sql, accessoriesBill);
            }
        }
    }//GEN-LAST:event_jTableServiceMouseClicked

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        // TODO add your handling code here:
        if (serviceBills.isEmpty() && accBills.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa chọn dịch vụ/linh kiện");
        } else {
            this.setVisible(false);
            BillView billView = new BillView(services, acclist, serviceBills, accBills, car, customer, bill);
            billView.setVisible(true);
            billView.setTitle("Hệ thống quản lý gara ô tô");
        }
    }//GEN-LAST:event_jButtonDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseServiceView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDone;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelCusName;
    private javax.swing.JLabel jLabelGetLicense;
    private javax.swing.JLabel jLabelGetMaker;
    private javax.swing.JLabel jLabelGetModel;
    private javax.swing.JLabel jLabelGetNote;
    private javax.swing.JLabel jLabelGetlName;
    private javax.swing.JLabel jLabelLicense;
    private javax.swing.JLabel jLabelMaker;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableService;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
